<!DOCTYPE html>
<!--
Copyright (c) 2014, Alexander Platonov
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
-->
<html style="width: 100%; height: 100%; margin:0px;">
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="js/dijit/themes/claro/claro.css" />
        <link rel="stylesheet" href="js/dojox/form/resources/ListInput.css" />
        <!--<link rel="stylesheet" href="js/dojox/grid/resources/Grid.css" />-->
        <link rel="stylesheet" href="js/dijit/themes/claro/document.css"/>
        <link rel="stylesheet" href="js/dojox/widget/Toaster/Toaster.css"/>
        <link rel="stylesheet" href="js/dojox/grid/resources/claroGrid.css"/>
        <link rel="stylesheet" href="js/dojox/form/resources/CheckedMultiSelect.css"/>
        <script src="js/dojo/dojo.js" data-dojo-config="isDebug: true, async: true"></script>
        <style type="text/css">

            body {
                padding: 30px;
                font: 12px Myriad,Helvetica,Tahoma,Arial,clean,sans-serif;
            }

            table.form td {
                padding: 5px;
            }
        </style>
    </style>
</head>
<body class="claro" style="width: 100%; height: 100%; margin:0px;">
    <script type="text/template" id="dialog-template">
        <div style="width:300px;">

        <div class="dijitDialogPaneContentArea">
        <div data-dojo-attach-point="contentNode">
        {form}              
        </div>
        </div>

        <div class="dijitDialogPaneActionBar">
        <div 
        class="message"
        data-dojo-attach-point="messageNode"                
        ></div>      
        <button
        data-dojo-type="dijit.form.Button"
        data-dojo-props=""                
        data-dojo-attach-point="submitButton"
        >
        OK
        </button>

        <button
        data-dojo-type="dijit.form.Button"
        data-dojo-attach-point="cancelButton"
        >
        Отмена
        </button>
        </div>      
        </div>
    </script>

    <script type="text/template" id="login-form-template">
        <form
        data-dojo-type="dijit.form.Form"
        data-dojo-attach-point="form"
        >

        <table class="form">
        <tr>
        <td>Имя</td>
        <td>
        <input data-dojo-type="dijit.form.ValidationTextBox"
        data-dojo-props='
        name: "username",
        required: true,
        maxLength: 64,
        trim: true,
        style: "width: 200px;"
        '
        />
        </td>
        </tr>

        <tr>
        <td>Пароль</td>
        <td>
        <input data-dojo-type="dijit.form.ValidationTextBox"
        type="password"
        data-dojo-props='
        name: "password",
        required: true,
        style: "width: 200px;"
        '
        />
        </td>
        </tr>

        </table>

        </form>
    </script>

    <script>
        require([
            "dojo/_base/declare",
            "dojo/_base/lang",
            "dojo/on",
            "dojo/dom",
            "dojo/Evented",
            "dojo/_base/Deferred",
            "dojo/json",
            "dijit/_Widget",
            "dijit/_TemplatedMixin",
            "dijit/_WidgetsInTemplateMixin",
            "dijit/Dialog",
            "dijit/form/Form",
            "dijit/form/ValidationTextBox",
            "dijit/form/Button",
            "dojo/request/xhr",
            "dojo/domReady!"
        ], function (
                declare,
                lang,
                on,
                dom,
                Evented,
                Deferred,
                JSON,
                _Widget,
                _TemplatedMixin,
                _WidgetsInTemplateMixin,
                Dialog,
                Form,
                ValidationTextBox,
                Button,
                xhr
                ) {

            var LoginDialog = declare([Dialog, Evented], {
                READY: 0,
                BUSY: 1,
                title: "Требуется аутентификация",
                message: "",
                busyLabel: "подождите...",
                // Binding property values to DOM nodes in templates
                // see: http://www.enterprisedojo.com/2010/10/02/lessons-in-widgetry-binding-property-values-to-dom-nodes-in-templates/
                attributeMap: lang.delegate(dijit._Widget.prototype.attributeMap, {
                    message: {
                        node: "messageNode",
                        type: "innerHTML"
                    }
                }),
                constructor: function (/*Object*/ kwArgs) {
                    lang.mixin(this, kwArgs);
                    var dialogTemplate = dom.byId("dialog-template").textContent;
                    var formTemplate = dom.byId("login-form-template").textContent;
                    var template = lang.replace(dialogTemplate, {
                        form: formTemplate
                    });

                    var contentWidget = new (declare(
                            [_Widget, _TemplatedMixin, _WidgetsInTemplateMixin],
                            {
                                templateString: template
                            }
                    ));
                    contentWidget.startup();
                    var content = this.content = contentWidget;
                    this.form = content.form;
                    // shortcuts
                    this.submitButton = content.submitButton;
                    this.cancelButton = content.cancelButton;
                    this.messageNode = content.messageNode;
                },
                postCreate: function () {
                    this.inherited(arguments);

                    this.readyState = this.READY;
                    this.okLabel = this.submitButton.get("label");

                    this.connect(this.submitButton, "onClick", "onSubmit");
                    this.connect(this.cancelButton, "onClick", "onCancel");

                    this.watch("readyState", lang.hitch(this, "_onReadyStateChange"));

                    this.form.watch("state", lang.hitch(this, "_onValidStateChange"));
                    this._onValidStateChange();
                },
                onSubmit: function () {
                    this.set("readyState", this.BUSY);
                    this.set("message", "");
                    var data = this.form.get("value");

                    var auth = this.controller.login(data);
                    var self=this;
                    auth.then(function(){self.onLoginSuccess();},function(){self.onLoginError();});
//                    Deferred.when(auth, lang.hitch(this, function (loginSuccess) {
//                        if (loginSuccess === true) {
//                            this.onLoginSuccess();
//                            return;
//                        }
//                        this.onLoginError();
//                    }));
                },
                onLoginSuccess: function () {
                    this.set("readyState", this.READY);
                    this.set("message", "Аутентификация успешно завершена!");
                    this.emit("success");
                    setTimeout("document.location.href='/'", 1000);
                },
                onLoginError: function () {
                    this.set("readyState", this.READY);
                    this.set("message", "Ошибка, попробуйте снова.");
                    this.emit("error");
                },
                onCancel: function () {
                    this.emit("cancel");
                },
                _onValidStateChange: function () {
                    this.submitButton.set("disabled", !!this.form.get("state").length);
                },
                _onReadyStateChange: function () {
                    var isBusy = this.get("readyState") == this.BUSY;
                    this.submitButton.set("label", isBusy ? this.busyLabel : this.okLabel);
                    this.submitButton.set("disabled", isBusy);
                }
            });

            var LoginController = declare(null, {
                constructor: function (kwArgs) {
                    lang.mixin(this, kwArgs);
                },
                login: function (data) {
                    // simulate calling web service for authentication
                    var def = new Deferred();
                    def = xhr("login",{
//                        handleAs:'json',
                        method:'POST',
                        data: data
                    });
                    return def;
                }
            });

            // provide username & password in constructor
            // since we do not have web service here to authenticate against    
            var loginController = new LoginController({username: "user", password: "user"});

            var loginDialog = new LoginDialog({controller: loginController});
            loginDialog.startup();
            loginDialog.show();

            loginDialog.on("cancel", function () {
                console.log("Login cancelled.");
            });

            loginDialog.on("error", function () {
                console.log("Login error.");
            });

            loginDialog.on("success", function () {
                console.log("Login success.");
                console.log(JSON.stringify(this.form.get("value")));
            });


        });

    </script>


</body>
</html>