<!DOCTYPE html>
<!--
Copyright (c) 2014, newworld
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
-->
<html style="width: 100%; height: 100%; margin:0px;">
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="js/dijit/themes/claro/claro.css" />
        <link rel="stylesheet" href="js/dojox/form/resources/ListInput.css" />
        <script src="js/dojo/dojo.js" data-dojo-config="isDebug: true, async: true"></script>
    </head>
    <body class="claro" style="width: 100%; height: 100%; margin:0px;">
        <div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="gutters:true,liveSplitters:true" style="width: 100%; height: 100%; margin:0px;">
            <!--<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'leading',splitter:true" style="width: 100px;"><div data-dojo-type="dijit/Tree" id="myTree"></div></div>-->
            <div data-dojo-type="dijit/layout/ContentPane"  data-dojo-props="region:'leading',splitter:true" id="contentForm" style="width:45%; height: 90%; margin:0px;"><div data-dojo-type="wm/userslist"  data-dojo-props="userStore:users" style="width: 100%; height: 100%; margin:0px;"></div></div>
            <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center',splitter:true"></div>
        </div>
        <script>
            require([
                "dojo/parser",
                "dijit/layout/BorderContainer",
                "dijit/layout/ContentPane",
                "wm/task",
                "wm/user",
                "dijit/Tree",
                "dojox/form/ListInput",
                "dojo/store/Memory",
                "wm/userslist",
                "dojo/dom",
                "dojo/dom-construct"
            ], function(parser, BorderContainer, ContentPane, task, user, Tree, ListInput, Memory, userslist, dom, domConstruct) {
                // Invoke the dojo/parser
                this.users = new Memory({data: [
                        {id: 1, name: "Синдряшко Николай Витальевич4", label: "<b>Синдряшко Николай Витальевич</b><i>нач отдела</i>", position: 'нач отдела'},
                        {id: 2, name: "Купцов Виталий Семёнович4", label: "<b>Купцов Виталий Семёнович</b><i>нач отдела</i>", position: 'нач отдела'},
                        {id: 3, name: "Сковородов Сергей Михайлович4", label: "<b>Сковородов Сергей Михайлович</b><i>нач отдела</i>", position: 'нач отдела'}
                    ]});
//                var task1 = new task({}, domConstruct.create('div'));
//                task1.placeAt(dom.byId('contentForm'));
//                task1.startup();
                  parser.parse();
            });
        </script>
    </body>
</html>